# Generated by Django 5.1.4 on 2025-09-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('membership_type', models.CharField(choices=[('student', 'IEEE Student Member'), ('member', 'IEEE Member'), ('non_ieee', 'Non-IEEE Member')], max_length=20)),
                ('ieee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('university_id', models.CharField(max_length=50)),
                ('answers', models.JSONField(default=dict)),
                ('payment_method', models.CharField(choices=[('Nagad', 'Nagad'), ('Bkash', 'Bkash')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('tshirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], max_length=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
