# Generated by Django 5.1.4 on 2024-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='unique_code',
            field=models.CharField(max_length=150),
            preserve_default=False,
        ),
    ]
