# Generated by Django 5.1.4 on 2024-12-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_session',
            name='order_of_session',
            field=models.IntegerField(default=0),
        ),
    ]
