# Generated by Django 5.1.4 on 2024-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_participant',
            name='university_id',
        ),
        migrations.AddField(
            model_name='registered_participant',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registered_participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registered_participant',
            name='t_shirt_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registered_participant',
            name='university',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
