# Generated by Django 5.1.4 on 2024-12-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_registered_participant_university_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_participant',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
