# Generated by Django 5.1.4 on 2024-12-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registered_participant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_participant',
            name='unique_code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
