# Generated by Django 5.1.4 on 2025-09-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_token_session_is_independent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Permission',
        ),
    ]
