# Generated by Django 5.1.4 on 2025-09-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registered_Participant',
            new_name='Form_Participant',
        ),
    ]
