# Generated by Django 5.1.4 on 2025-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_participant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
