# Generated by Django 5.1.4 on 2025-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_form_participant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="form_participant",
            name="affiliation",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_participant",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_participant",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="form_participant",
            name="profession",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="form_participant",
            name="department",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="form_participant",
            name="university",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="form_participant",
            name="university_id",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
