# Generated by Django 5.1.4 on 2025-09-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_form_participant_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventformstatus',
            options={'verbose_name': 'Event Form Status'},
        ),
        migrations.AlterModelOptions(
            name='form_participant',
            options={'verbose_name': 'Form Participant'},
        ),
    ]
