# Generated by Django 5.1.4 on 2025-09-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_eventformstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_participant',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_participant',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], max_length=5, null=True),
        ),
    ]
