# Generated by Django 5.1.4 on 2025-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_form_participant_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Shirt_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('ieee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tshirt_size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'T-Shirt Form',
            },
        ),
    ]
