# Generated by Django 5.1.4 on 2025-09-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'verbose_name': 'Error Log'},
        ),
    ]
